import socket
import threading
from tkinter import *
from cryptography.fernet import Fernet
import re

# Use the same key as the server
key = b'7Ht-HcyIUnRI8DQHYbiSdBPkVDC0-NFxiTiVfud5yUk='  # Put the key generated by server here
cipher_suite = Fernet(key)

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)  # Define the client here

def start_client():
    client.connect(('localhost', 50000))
    threading.Thread(target=message_handler, args=(client,)).start()

    window.mainloop()
    client.close()

def message_handler(client):
    while True:
        message = client.recv(1024)

        # Decrypt the message
        decrypted_message = cipher_suite.decrypt(message)
        print("Received message: ", decrypted_message.decode())

        msg_list.insert(END, decrypted_message.decode())

def send_message(event=None):  # Adjusted here
    message = my_msg.get()
    my_msg.set("")  # Clears the input field

    # Encrypt the message
    encrypted_message = cipher_suite.encrypt(message.encode())

    client.send(encrypted_message)  # Adjusted here

window = Tk()
window.title("Chat App")

messages_frame = Frame(window)
my_msg = StringVar()  # For the messages to be sent
my_msg.set("Type your messages here.")
scrollbar = Scrollbar(messages_frame)  # To navigate through past messages
msg_list = Listbox(messages_frame, height=15, width=50, yscrollcommand=scrollbar.set)
scrollbar.pack(side=RIGHT, fill=Y)
msg_list.pack(side=LEFT, fill=BOTH)
msg_list.pack()
messages_frame.pack()

entry_field = Entry(window, textvariable=my_msg)
entry_field.bind("<Return>", send_message)
entry_field.pack()
send_button = Button(window, text="Send", command=send_message)
send_button.pack()

window.protocol("WM_DELETE_WINDOW", window.quit)

# Start the client
start_client()
